### ISSUE TITLE
dgram.js:274     throw new RangeError

### ISSUE THREAD

**Issue by jarradh** [arcadia-unity/repl-sublimetext#3]
$ cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/SublimeREPL/config/Clojure
$ git clone https://github.com/clojure-unity/repl-sublimetext.git Unity

Launch Sublime Text 3 (dev channel build 3118)

Tools > SublimeREPL > Clojure > Unity

```
dgram.js:274
    throw new RangeError('Offset + length beyond buffer length');
    ^

RangeError: Offset + length beyond buffer length
    at Socket.send (dgram.js:274:11)
    at Object.<anonymous> (/Users/<USER>/Library/Application Support/Sublime Text 3/Packages/SublimeREPL/config/Clojure/Unity/repl.js:45:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

***Repl Closed***
```

**Comment by nasser** [comment]
What version of node are you on?

**Comment by JacobGood1** [comment]
I had this same error till I updated node.js, probably should close this now...
